baseURL = "http://pho-doc.nprod.net"
languageCode = "en-us"
title = "PHO documentation"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  customMermaidURL = "https://unpkg.com/mermaid@8.8.3/dist/mermaid.min.js"
  author = "Jonathan Bisson"
  description = "PHO documentation"
  themeVariant = "green"
  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Home"